sudo: required
services:
  # We need docker installed for the build.
  - docker
before_install:
  # Decrypt service-account.json to get google cloud service account auth.
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # Download and install the google cloud SDK.
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # Apply google cloud SDK config into our environment.
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl.
  - gcloud components update kubectl
  # Authenticate with google cloud.
  - gcloud auth activate-service-account --key-file service-account.json
