sudo: required
services:
  # We need docker installed for the build.
  - docker
env:
  global:
    # Define an environment variable to be used in our deploy script.
    - GIT_SHA=$(git rev-parse HEAD)
    # Tell the gcloud SDK to not prompt us since we're automating.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # Decrypt service-account.json to get google cloud service account auth.
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # Download and install the google cloud SDK.
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # Apply google cloud SDK config into our environment.
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl.
  - gcloud components update kubectl
  # Authenticate with google cloud.
  - gcloud auth activate-service-account --key-file service-account.json
  # Configure environment to use our project.
  - gcloud config set project multi-k8s-253419
  # Configure compute zone for our cluster.
  - gcloud config set compute/zone us-central1-a
  # Configure the cluster to use.
  - gcloud container clusters get-credentials multi-cluster
  # Login to docker.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Build test image for multi-client.
  - docker build -t mriedem/react-test -f ./client/Dockerfile.dev ./client
script:
  # Run tests.
  - docker run -e CI=true USERNAME/react-test npm run test
deploy:
  # Use our custom deploy script.
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
