apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # Give me a 2gig volume that can only be used by a single node.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi