apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  # Manage 3 pods in this deployment using the same multi-server container.
  replicas: 3
  # This deployment is going to manage the 'server' component.
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: mriedem/multi-server
          ports:
            # The server app is hard-coded to listen on port 5000.
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              # Get the value for PGPASSWORD from the secret
              # object named "pgpassword". The 'key' is what we
              # used for the key when creating the secret.
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD